CREATE EXTENSION IF NOT EXISTS postgis;
CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE EXTENSION IF NOT EXISTS postgis;

CREATE TABLE "Amenities" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "IconName" text NOT NULL,
    "Name" jsonb NOT NULL,
    "Description" jsonb,
    "Type" integer NOT NULL,
    "IsActive" boolean NOT NULL,
    CONSTRAINT "PK_Amenities" PRIMARY KEY ("Id")
);

CREATE TABLE "Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Email" text NOT NULL,
    "PasswordHash" text NOT NULL,
    "Role" integer NOT NULL,
    "IsEmailVerified" boolean NOT NULL,
    "RefreshToken" text,
    "RefreshTokenExpiry" timestamp with time zone NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "LastLoginAt" timestamp with time zone,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

CREATE TABLE "BlogPosts" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "AuthorId" integer NOT NULL,
    "Title" jsonb NOT NULL,
    "Content" jsonb NOT NULL,
    "Slug" jsonb NOT NULL,
    "FeaturedImageUrl" text,
    "IsPublished" boolean NOT NULL,
    "PublishedAt" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "ViewCount" integer NOT NULL,
    CONSTRAINT "PK_BlogPosts" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_BlogPosts_Users_AuthorId" FOREIGN KEY ("AuthorId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Listings" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "HostId" integer NOT NULL,
    "Type" integer NOT NULL,
    "IsActive" boolean NOT NULL,
    "Title" jsonb NOT NULL,
    "Description" jsonb NOT NULL,
    "Address" jsonb NOT NULL,
    "Location" geography (point),
    "Latitude" numeric NOT NULL,
    "Longitude" numeric NOT NULL,
    "MaxGuestCount" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "Rating" numeric NOT NULL,
    "ReviewCount" integer NOT NULL,
    CONSTRAINT "PK_Listings" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Listings_Users_HostId" FOREIGN KEY ("HostId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Notifications" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "Type" integer NOT NULL,
    "Title" text NOT NULL,
    "Message" text NOT NULL,
    "ActionUrl" text,
    "IsRead" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Notifications" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Notifications_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "UserProfiles" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "FirstName" jsonb NOT NULL,
    "LastName" jsonb NOT NULL,
    "PhoneNumber" text,
    "ProfileImageUrl" text,
    "Bio" jsonb,
    CONSTRAINT "PK_UserProfiles" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UserProfiles_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AvailabilityBlocks" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ListingId" integer NOT NULL,
    "StartDateTime" timestamp with time zone NOT NULL,
    "EndDateTime" timestamp with time zone NOT NULL,
    "IsBlocked" boolean NOT NULL,
    "Reason" text,
    CONSTRAINT "PK_AvailabilityBlocks" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AvailabilityBlocks_Listings_ListingId" FOREIGN KEY ("ListingId") REFERENCES "Listings" ("Id") ON DELETE CASCADE
);

CREATE TABLE "DailyPricings" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ListingId" integer NOT NULL,
    "Date" date NOT NULL,
    "Price" numeric NOT NULL,
    "HourlyPrice" numeric,
    "IsAvailable" boolean NOT NULL,
    "Notes" text,
    CONSTRAINT "PK_DailyPricings" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_DailyPricings_Listings_ListingId" FOREIGN KEY ("ListingId") REFERENCES "Listings" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Favorites" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "ListingId" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Favorites" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Favorites_Listings_ListingId" FOREIGN KEY ("ListingId") REFERENCES "Listings" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Favorites_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "ListingAmenities" (
    "ListingId" integer NOT NULL,
    "AmenityId" integer NOT NULL,
    CONSTRAINT "PK_ListingAmenities" PRIMARY KEY ("ListingId", "AmenityId"),
    CONSTRAINT "FK_ListingAmenities_Amenities_AmenityId" FOREIGN KEY ("AmenityId") REFERENCES "Amenities" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ListingAmenities_Listings_ListingId" FOREIGN KEY ("ListingId") REFERENCES "Listings" ("Id") ON DELETE CASCADE
);

CREATE TABLE "ListingImages" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ListingId" integer NOT NULL,
    "ImageUrl" text NOT NULL,
    "DisplayOrder" integer NOT NULL,
    "IsPrimary" boolean NOT NULL,
    "AltText" jsonb,
    CONSTRAINT "PK_ListingImages" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ListingImages_Listings_ListingId" FOREIGN KEY ("ListingId") REFERENCES "Listings" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Reservations" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ListingId" integer NOT NULL,
    "GuestId" integer NOT NULL,
    "BookingType" integer NOT NULL,
    "StartTime" timestamp with time zone NOT NULL,
    "EndTime" timestamp with time zone NOT NULL,
    "GuestCount" integer NOT NULL,
    "UnitPrice" numeric NOT NULL,
    "UnitCount" integer NOT NULL,
    "TotalPrice" numeric NOT NULL,
    "DiscountAmount" numeric,
    "FinalPrice" numeric NOT NULL,
    "Status" integer NOT NULL,
    "SpecialRequests" jsonb,
    "CreatedAt" timestamp with time zone NOT NULL,
    "ConfirmedAt" timestamp with time zone,
    "CancelledAt" timestamp with time zone,
    "CancellationReason" text,
    CONSTRAINT "PK_Reservations" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Reservations_Listings_ListingId" FOREIGN KEY ("ListingId") REFERENCES "Listings" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Reservations_Users_GuestId" FOREIGN KEY ("GuestId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "ReservationPayments" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ReservationId" integer NOT NULL,
    "Provider" text NOT NULL,
    "ProviderTransactionId" text,
    "Amount" numeric NOT NULL,
    "Currency" text NOT NULL,
    "Status" integer NOT NULL,
    "PaidAt" timestamp with time zone,
    "RefundedAt" timestamp with time zone,
    "RefundedAmount" numeric,
    CONSTRAINT "PK_ReservationPayments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ReservationPayments_Reservations_ReservationId" FOREIGN KEY ("ReservationId") REFERENCES "Reservations" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Reviews" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ReservationId" integer NOT NULL,
    "ListingId" integer NOT NULL,
    "GuestId" integer NOT NULL,
    "Rating" integer NOT NULL,
    "Comment" jsonb NOT NULL,
    "HostResponse" jsonb,
    "HostResponseDate" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL,
    "IsVerified" boolean NOT NULL,
    CONSTRAINT "PK_Reviews" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Reviews_Listings_ListingId" FOREIGN KEY ("ListingId") REFERENCES "Listings" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Reviews_Reservations_ReservationId" FOREIGN KEY ("ReservationId") REFERENCES "Reservations" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Reviews_Users_GuestId" FOREIGN KEY ("GuestId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_AvailabilityBlocks_ListingId" ON "AvailabilityBlocks" ("ListingId");

CREATE INDEX "IX_BlogPosts_AuthorId" ON "BlogPosts" ("AuthorId");

CREATE INDEX "IX_BlogPosts_Title" ON "BlogPosts" USING gin ("Title");

CREATE INDEX "IX_DailyPricings_ListingId_Date" ON "DailyPricings" ("ListingId", "Date");

CREATE INDEX "IX_Favorites_ListingId" ON "Favorites" ("ListingId");

CREATE UNIQUE INDEX "IX_Favorites_UserId_ListingId" ON "Favorites" ("UserId", "ListingId");

CREATE INDEX "IX_ListingAmenities_AmenityId" ON "ListingAmenities" ("AmenityId");

CREATE INDEX "IX_ListingImages_ListingId" ON "ListingImages" ("ListingId");

CREATE INDEX "IX_Listings_Description" ON "Listings" USING gin ("Description");

CREATE INDEX "IX_Listings_HostId" ON "Listings" ("HostId");

CREATE INDEX "IX_Listings_IsActive" ON "Listings" ("IsActive");

CREATE INDEX "IX_Listings_Location" ON "Listings" USING gist ("Location");

CREATE INDEX "IX_Listings_Title" ON "Listings" USING gin ("Title");

CREATE INDEX "IX_Listings_Type" ON "Listings" ("Type");

CREATE INDEX "IX_Notifications_UserId" ON "Notifications" ("UserId");

CREATE UNIQUE INDEX "IX_ReservationPayments_ReservationId" ON "ReservationPayments" ("ReservationId");

CREATE INDEX "IX_Reservations_GuestId" ON "Reservations" ("GuestId");

CREATE INDEX "IX_Reservations_ListingId" ON "Reservations" ("ListingId");

CREATE INDEX "IX_Reservations_StartTime" ON "Reservations" ("StartTime");

CREATE INDEX "IX_Reservations_Status" ON "Reservations" ("Status");

CREATE INDEX "IX_Reviews_GuestId" ON "Reviews" ("GuestId");

CREATE INDEX "IX_Reviews_ListingId" ON "Reviews" ("ListingId");

CREATE UNIQUE INDEX "IX_Reviews_ReservationId" ON "Reviews" ("ReservationId");

CREATE UNIQUE INDEX "IX_UserProfiles_UserId" ON "UserProfiles" ("UserId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260120200045_InitialCreate', '8.0.11');

COMMIT;

START TRANSACTION;

ALTER TABLE "ReservationPayments" ADD "CreatedAt" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';

ALTER TABLE "Listings" ADD "BasePricePerDay" numeric NOT NULL DEFAULT 0.0;

ALTER TABLE "Listings" ADD "BasePricePerHour" numeric NOT NULL DEFAULT 0.0;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260120202339_UpdateListingAndPayment', '8.0.11');

COMMIT;

START TRANSACTION;

ALTER TABLE "Favorites" DROP CONSTRAINT "FK_Favorites_Listings_ListingId";

DROP INDEX "IX_Listings_IsActive";

DROP INDEX "IX_Favorites_ListingId";

DROP INDEX "IX_Favorites_UserId_ListingId";

ALTER TABLE "Reviews" DROP COLUMN "Comment";

ALTER TABLE "ReservationPayments" DROP COLUMN "Provider";

ALTER TABLE "ListingImages" DROP COLUMN "AltText";

ALTER TABLE "AvailabilityBlocks" DROP COLUMN "EndDateTime";

ALTER TABLE "AvailabilityBlocks" DROP COLUMN "StartDateTime";

ALTER TABLE "Amenities" DROP COLUMN "Type";

ALTER TABLE "UserProfiles" RENAME COLUMN "ProfileImageUrl" TO "Avatar";

ALTER TABLE "Reviews" RENAME COLUMN "HostResponse" TO "Categories";

ALTER TABLE "ReservationPayments" RENAME COLUMN "RefundedAmount" TO "RefundAmount";

ALTER TABLE "ListingImages" RENAME COLUMN "IsPrimary" TO "IsCover";

ALTER TABLE "ListingImages" RENAME COLUMN "ImageUrl" TO "Url";

ALTER TABLE "Favorites" RENAME COLUMN "ListingId" TO "VenueType";

ALTER TABLE "BlogPosts" RENAME COLUMN "FeaturedImageUrl" TO "ImageUrl";

ALTER TABLE "AvailabilityBlocks" RENAME COLUMN "IsBlocked" TO "IsAvailable";

ALTER TABLE "Amenities" RENAME COLUMN "Name" TO "Label";

ALTER TABLE "Amenities" RENAME COLUMN "IconName" TO "Icon";

ALTER TABLE "Amenities" RENAME COLUMN "Description" TO "ApplicableTo";

ALTER TABLE "Users" ALTER COLUMN "Id" TYPE uuid;
ALTER TABLE "Users" ALTER COLUMN "Id" DROP IDENTITY;

ALTER TABLE "Users" ADD "LanguageSettings" jsonb NOT NULL DEFAULT '{}';

ALTER TABLE "Users" ADD "MembershipLevel" text NOT NULL DEFAULT '';

ALTER TABLE "Users" ADD "NotificationSettings" jsonb NOT NULL DEFAULT '{}';

ALTER TABLE "Users" ADD "PrivacySettings" jsonb NOT NULL DEFAULT '{}';

ALTER TABLE "Users" ADD "Status" integer NOT NULL DEFAULT 0;

ALTER TABLE "UserProfiles" ALTER COLUMN "UserId" TYPE uuid;

ALTER TABLE "UserProfiles" ALTER COLUMN "Id" TYPE uuid;
ALTER TABLE "UserProfiles" ALTER COLUMN "Id" DROP IDENTITY;

ALTER TABLE "Reviews" ALTER COLUMN "ReservationId" TYPE uuid;

ALTER TABLE "Reviews" ALTER COLUMN "ListingId" TYPE uuid;

ALTER TABLE "Reviews" ALTER COLUMN "GuestId" TYPE uuid;

ALTER TABLE "Reviews" ALTER COLUMN "Id" TYPE uuid;
ALTER TABLE "Reviews" ALTER COLUMN "Id" DROP IDENTITY;

ALTER TABLE "Reviews" ADD "HostResponseText" text;

ALTER TABLE "Reviews" ADD "Text" text NOT NULL DEFAULT '';

ALTER TABLE "Reservations" ALTER COLUMN "ListingId" TYPE uuid;

ALTER TABLE "Reservations" ALTER COLUMN "GuestId" TYPE uuid;

ALTER TABLE "Reservations" ALTER COLUMN "Id" TYPE uuid;
ALTER TABLE "Reservations" ALTER COLUMN "Id" DROP IDENTITY;

ALTER TABLE "Reservations" ADD "CheckInCode" text;

ALTER TABLE "Reservations" ADD "CheckedInAt" timestamp with time zone;

ALTER TABLE "Reservations" ADD "ConfirmationNumber" text;

ALTER TABLE "Reservations" ADD "Currency" text NOT NULL DEFAULT '';

ALTER TABLE "Reservations" ADD "Guests" jsonb;

ALTER TABLE "Reservations" ADD "PriceBreakdown" jsonb;

ALTER TABLE "Reservations" ADD "Selections" jsonb;

ALTER TABLE "Reservations" ADD "VenueType" integer NOT NULL DEFAULT 0;

ALTER TABLE "ReservationPayments" ALTER COLUMN "ReservationId" TYPE uuid;

ALTER TABLE "ReservationPayments" ALTER COLUMN "Id" TYPE uuid;
ALTER TABLE "ReservationPayments" ALTER COLUMN "Id" DROP IDENTITY;

ALTER TABLE "ReservationPayments" ADD "PaymentIntentId" text;

ALTER TABLE "ReservationPayments" ADD "PaymentMethodId" uuid;

ALTER TABLE "Notifications" ALTER COLUMN "UserId" TYPE uuid;

ALTER TABLE "Notifications" ALTER COLUMN "Id" TYPE uuid;
ALTER TABLE "Notifications" ALTER COLUMN "Id" DROP IDENTITY;

ALTER TABLE "Notifications" ADD "ReadAt" timestamp with time zone;

ALTER TABLE "Listings" ALTER COLUMN "HostId" TYPE uuid;

ALTER TABLE "Listings" ALTER COLUMN "Id" TYPE uuid;
ALTER TABLE "Listings" ALTER COLUMN "Id" DROP IDENTITY;

ALTER TABLE "Listings" ADD "City" text NOT NULL DEFAULT '';

ALTER TABLE "Listings" ADD "Conditions" jsonb;

ALTER TABLE "Listings" ADD "Country" text NOT NULL DEFAULT '';

ALTER TABLE "Listings" ADD "Duration" text;

ALTER TABLE "Listings" ADD "IsFeatured" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "Listings" ADD "IsSuperhost" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "Listings" ADD "PriceCurrency" text NOT NULL DEFAULT '';

ALTER TABLE "Listings" ADD "PriceRangeMax" numeric;

ALTER TABLE "Listings" ADD "PriceRangeMin" numeric;

ALTER TABLE "Listings" ADD "RejectionReason" text;

ALTER TABLE "Listings" ADD "Slug" text NOT NULL DEFAULT '';

ALTER TABLE "Listings" ADD "SpotCount" integer NOT NULL DEFAULT 0;

ALTER TABLE "Listings" ADD "Status" integer NOT NULL DEFAULT 0;

ALTER TABLE "ListingImages" ALTER COLUMN "ListingId" TYPE uuid;

ALTER TABLE "ListingImages" ALTER COLUMN "Id" TYPE uuid;
ALTER TABLE "ListingImages" ALTER COLUMN "Id" DROP IDENTITY;

ALTER TABLE "ListingImages" ADD "Alt" text;

ALTER TABLE "ListingAmenities" ALTER COLUMN "AmenityId" TYPE uuid;

ALTER TABLE "ListingAmenities" ALTER COLUMN "ListingId" TYPE uuid;

ALTER TABLE "ListingAmenities" ADD "IsEnabled" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "Favorites" ALTER COLUMN "UserId" TYPE uuid;

ALTER TABLE "Favorites" ALTER COLUMN "Id" TYPE uuid;
ALTER TABLE "Favorites" ALTER COLUMN "Id" DROP IDENTITY;

ALTER TABLE "Favorites" ADD "VenueId" uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000';

ALTER TABLE "DailyPricings" ALTER COLUMN "ListingId" TYPE uuid;

ALTER TABLE "DailyPricings" ALTER COLUMN "Id" TYPE uuid;
ALTER TABLE "DailyPricings" ALTER COLUMN "Id" DROP IDENTITY;

ALTER TABLE "DailyPricings" ADD "Label" text;

ALTER TABLE "BlogPosts" ALTER COLUMN "Slug" TYPE text;

ALTER TABLE "BlogPosts" ALTER COLUMN "AuthorId" TYPE uuid;

ALTER TABLE "BlogPosts" ALTER COLUMN "Id" TYPE uuid;
ALTER TABLE "BlogPosts" ALTER COLUMN "Id" DROP IDENTITY;

ALTER TABLE "BlogPosts" ADD "Category" text;

ALTER TABLE "BlogPosts" ADD "Description" jsonb NOT NULL DEFAULT '{}';

ALTER TABLE "BlogPosts" ADD "IsFeatured" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "BlogPosts" ADD "ReadTime" integer NOT NULL DEFAULT 0;

ALTER TABLE "BlogPosts" ADD "Tags" jsonb;

ALTER TABLE "AvailabilityBlocks" ALTER COLUMN "ListingId" TYPE uuid;

ALTER TABLE "AvailabilityBlocks" ALTER COLUMN "Id" TYPE uuid;
ALTER TABLE "AvailabilityBlocks" ALTER COLUMN "Id" DROP IDENTITY;

ALTER TABLE "AvailabilityBlocks" ADD "CustomPrice" numeric;

ALTER TABLE "AvailabilityBlocks" ADD "EndDate" date NOT NULL DEFAULT DATE '-infinity';

ALTER TABLE "AvailabilityBlocks" ADD "StartDate" date NOT NULL DEFAULT DATE '-infinity';

ALTER TABLE "Amenities" ALTER COLUMN "Id" TYPE uuid;
ALTER TABLE "Amenities" ALTER COLUMN "Id" DROP IDENTITY;

ALTER TABLE "Amenities" ADD "Category" text;

ALTER TABLE "Amenities" ADD "CreatedAt" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';

CREATE TABLE "Cities" (
    "Id" uuid NOT NULL,
    "Name" jsonb NOT NULL,
    "Country" text NOT NULL,
    "Latitude" numeric NOT NULL,
    "Longitude" numeric NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Cities" PRIMARY KEY ("Id")
);

CREATE TABLE "NewsletterSubscribers" (
    "Id" uuid NOT NULL,
    "Email" text NOT NULL,
    "IsActive" boolean NOT NULL,
    "SubscribedAt" timestamp with time zone NOT NULL,
    "UnsubscribedAt" timestamp with time zone,
    CONSTRAINT "PK_NewsletterSubscribers" PRIMARY KEY ("Id")
);

CREATE TABLE "PaymentMethods" (
    "Id" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "Type" text NOT NULL,
    "Brand" integer NOT NULL,
    "Last4" text NOT NULL,
    "ExpiryMonth" integer NOT NULL,
    "ExpiryYear" integer NOT NULL,
    "IsDefault" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "ProviderToken" text,
    CONSTRAINT "PK_PaymentMethods" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PaymentMethods_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX "IX_Reservations_ConfirmationNumber" ON "Reservations" ("ConfirmationNumber");

CREATE INDEX "IX_ReservationPayments_PaymentMethodId" ON "ReservationPayments" ("PaymentMethodId");

CREATE INDEX "IX_Listings_City" ON "Listings" ("City");

CREATE INDEX "IX_Listings_IsFeatured" ON "Listings" ("IsFeatured");

CREATE UNIQUE INDEX "IX_Listings_Slug" ON "Listings" ("Slug");

CREATE INDEX "IX_Listings_Status" ON "Listings" ("Status");

CREATE UNIQUE INDEX "IX_Favorites_UserId_VenueId_VenueType" ON "Favorites" ("UserId", "VenueId", "VenueType");

CREATE INDEX "IX_Favorites_VenueId" ON "Favorites" ("VenueId");

CREATE INDEX "IX_BlogPosts_IsFeatured" ON "BlogPosts" ("IsFeatured");

CREATE INDEX "IX_BlogPosts_IsPublished" ON "BlogPosts" ("IsPublished");

CREATE UNIQUE INDEX "IX_BlogPosts_Slug" ON "BlogPosts" ("Slug");

CREATE INDEX "IX_Cities_Country" ON "Cities" ("Country");

CREATE UNIQUE INDEX "IX_NewsletterSubscribers_Email" ON "NewsletterSubscribers" ("Email");

CREATE INDEX "IX_PaymentMethods_UserId" ON "PaymentMethods" ("UserId");

ALTER TABLE "Favorites" ADD CONSTRAINT "FK_Favorites_Listings_VenueId" FOREIGN KEY ("VenueId") REFERENCES "Listings" ("Id");

ALTER TABLE "ReservationPayments" ADD CONSTRAINT "FK_ReservationPayments_PaymentMethods_PaymentMethodId" FOREIGN KEY ("PaymentMethodId") REFERENCES "PaymentMethods" ("Id");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260203195702_Phase5_SchemaUpdates', '8.0.11');

COMMIT;

START TRANSACTION;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260203204644_InitialCreateV2', '8.0.11');

COMMIT;

START TRANSACTION;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260203204854_InitialCreateV3', '8.0.11');

COMMIT;

